// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaP8_COv70JOKSBEcsZP_9UvcqqS9MUwM',
    appId: '1:628451981222:web:7c74c3f2ac961ab8d68167',
    messagingSenderId: '628451981222',
    projectId: 'ecommerce-ad194',
    authDomain: 'ecommerce-ad194.firebaseapp.com',
    databaseURL: 'https://ecommerce-ad194-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-ad194.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0HyWdwWNvC8uyzFuCOmxrBuwFBl409Sg',
    appId: '1:628451981222:android:ed6277d89788dc26d68167',
    messagingSenderId: '628451981222',
    projectId: 'ecommerce-ad194',
    databaseURL: 'https://ecommerce-ad194-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-ad194.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYKx4UHMgqSjJMwqi09IIq6s_jCblxLtA',
    appId: '1:628451981222:ios:bfc3bb45905873ded68167',
    messagingSenderId: '628451981222',
    projectId: 'ecommerce-ad194',
    databaseURL: 'https://ecommerce-ad194-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-ad194.appspot.com',
    iosClientId: '628451981222-6bt2hk2uufjl4pdnq6frd4tmqlf90ruu.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYKx4UHMgqSjJMwqi09IIq6s_jCblxLtA',
    appId: '1:628451981222:ios:5bc98c5d952f1fa2d68167',
    messagingSenderId: '628451981222',
    projectId: 'ecommerce-ad194',
    databaseURL: 'https://ecommerce-ad194-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-ad194.appspot.com',
    iosClientId: '628451981222-osfn9g27ufijclmj5ps9k9g0vkrj5d6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp.RunnerTests',
  );
}
